Updated snapcraft configuration

diff --git a/snap/configure b/snap/configure
--- a/snap/configure
+++ b/snap/configure
@@ -1,2 +1,2 @@
-#!/bin/sh -e
-bin/diode_node rpc 'Diode.Config.configure()'
+#!/bin/sh
+${SNAP}/bin/diode_node rpc 'Diode.Config.configure()' || echo "Configure failed"
